theme = "catppuccin_macchiato"

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = false
scrolloff = 20
scroll-lines = 3
shell = ["fish", "-c"]
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-pairs = false
true-color = true
cursorline = true
[editor.file-picker]
hidden = false
[editor.inline-diagnostics]
cursor-line = "error"

[editor.statusline]
left = ["mode", "workspace-diagnostics", "spinner"]
center = ["file-name"]
right = ["total-line-numbers", "position", "position-percentage", "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.indent-guides]
render = true

[keys.normal.space.u]
i = ":toggle lsp.display-inlay-hints"
